name = "Dragon863"
license = "MIT"
licenselink = "https://github.com/Dragon863/Site-Hugo/blob/main/themes/dragon863/LICENSE"
description = "A custom theme for Hugo, designed using MD3 for my personal blog."
homepage = "https://danieldb.uk/"
tags = []
features = []
min_version = "0.41.0"

[author]
name = "Daniel B"
homepage = "https://danieldb.uk/"
